[package]
name = "time_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
chrono-tz = "0.8.4"
rouille = "3.6.2"
serde = "1.0.193"
serde_derive = "1.0.193"
